debian/open-switcher.desktop usr/share/applications/
debian/autostart/open-switcher-autostart.desktop etc/xdg/autostart/
debian/scripts/open-switcher-input-access-maintenance usr/lib/open-switcher/
debian/scripts/open-switcher-launch usr/lib/open-switcher/
debian/scripts/open-switcher-user-session-start usr/lib/open-switcher/
debian/scripts/open-switcher-user-session-stop usr/lib/open-switcher/
dist/icons/hicolor/512x512/apps/open-switcher.png usr/share/icons/hicolor/512x512/apps/
